[tool.poetry]
name = "tg-bot"
version = "0.1.0"
description = ""
authors = ["aa35037123 <wesleyshi0321@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytelegrambotapi = "^4.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
